=== theodore-evans/glomeruli-segmentation/ead-app-schema-draft-1.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "required": [
        "name",
        "namespace",
        "description",
        "inputs",
        "outputs"
    ],
    "properties": {
        "$schema": { 
    
        },
        "id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "namespace": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "classes": {
            "type": "object",
            "patternProperties": {
                "^[a-zA-Z0-9_-]+$": {
                    "oneOf": [
                        { "$ref": "#definitions/class_leaf" },
                        { "$ref": "#definitions/class_node" }
                    ]
                }
            },
            "additionalProperties": false
        },
        "inputs": {
            "additionalProperties": {
                "$ref": "#definitions/io_data"   
            }
        },
        "outputs": {
            "additionalProperties": {
                "$ref": "#definitions/io_data"   
            }
        }
    },
    "additionalProperties": false,

    "definitions": {

        "class_node": {
            "type": "object",
            "patternProperties": {
                "^[a-zA-Z0-9_-]+$": {
                    "oneOf": [
                        { "$ref": "#definitions/class_leaf" },
                        { "$ref": "#definitions/class_node" }
                    ]
                }
            },
            "additionalProperties": false
        },
        "class_leaf": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "mapping": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "io_data": {
            "type": "object",
            "oneOf": [
                { "$ref": "#/definitions/bool" },
                { "$ref": "#/definitions/integer" },
                { "$ref": "#/definitions/float" },
                { "$ref": "#/definitions/string" },
                { "$ref": "#/definitions/collection" },
                { "$ref": "#/definitions/wsi" },
                { "$ref": "#/definitions/class" },
                { "$ref": "#/definitions/point" },
                { "$ref": "#/definitions/line" },
                { "$ref": "#/definitions/arrow" },
                { "$ref": "#/definitions/rectangle" },
                { "$ref": "#/definitions/polygon" },
                { "$ref": "#/definitions/circle" }
            ]
        },
        "bool": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "const": "bool"
                },
                "description": {
                    "type": "string"
                },
                "optional": {
                    "type": "boolean"
                },
                "default": {
                    "type": "boolean"
                },
                "reference": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "integer": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "const": "integer"
                },
                "min": {
                    "type": "number"
                },
                "max": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "optional": {
                    "type": "boolean"
                },
                "default": {
                    "type": "number"
                },
                "reference": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "float": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "const": "float"
                },
                "minimum": {
                    "type": "number"
                },
                "maximum": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "optional": {
                    "type": "boolean"
                },
                "default": {
                    "type": "number"
                },
                "reference": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "string": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "const": "string"
                },
                "description": {
                    "type": "string"
                },
                "optional": {
                    "type": "boolean"
                },
                "default": {
                    "type": "string"
                },
                "reference": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "collection": {
            "type": "object",
            "required": [
                "type",
                "items"
            ],
            "properties": {
                "type": {
                    "const": "collection"
                },
                "items": {
                    "type": "object",
                    "anyOf": [
                        { "$ref": "#/definitions/bool" },
                        { "$ref": "#/definitions/integer" },
                        { "$ref": "#/definitions/float" },
                        { "$ref": "#/definitions/string" },
                        { "$ref": "#/definitions/collection" },
                        { "$ref": "#/definitions/wsi" },
                        { "$ref": "#/definitions/class" },
                        { "$ref": "#/definitions/point" },
                        { "$ref": "#/definitions/line" },
                        { "$ref": "#/definitions/arrow" },
                        { "$ref": "#/definitions/rectangle" },
                        { "$ref": "#/definitions/polygon" },
                        { "$ref": "#/definitions/circle" }
                    ]
                },
                "min_size": {
                    "type": "number",
                    "minimum": 0
                },
                "max_size": {
                    "type": "number",
                    "minimum": 1
                },
                "description": {
                    "type": "string"
                },
                "optional": {
                    "type": "boolean"
                },
                "reference": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "point": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "const": "point"
                },
                "description": {
                    "type": "string"
                },
                "optional": {
                    "type": "boolean"
                },
                "reference": {
                    "type": "string"
                },
                "classes": {
                    "type": "array"
                }
            },
            "additionalProperties": false
        },
        "line": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "const": "line"
                },
                "description": {
                    "type": "string"
                },
                "optional": {
                    "type": "boolean"
                },
                "reference": {
                    "type": "string"
                },
                "classes": {
                    "type": "array"
                }
            },
            "additionalProperties": false
        },
        "arrow": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "const": "arrow"
                },
                "description": {
                    "type": "string"
                },
                "optional": {
                    "type": "boolean"
                },
                "reference": {
                    "type": "string"
                },
                "classes": {
                    "type": "array"
                }
            },
            "additionalProperties": false
        },
        "rectangle": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "const": "rectangle"
                },
                "description": {
                    "type": "string"
                },
                "optional": {
                    "type": "boolean"
                },
                "reference": {
                    "type": "string"
                },
                "classes": {
                    "type": "array"
                }
            },
            "additionalProperties": false
        },
        "polygon": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "const": "polygon"
                },
                "description": {
                    "type": "string"
                },
                "optional": {
                    "type": "boolean"
                },
                "reference": {
                    "type": "string"
                },
                "classes": {
                    "type": "array"
                }
            },
            "additionalProperties": false
        },
        "circle": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "const": "circle"
                },
                "description": {
                    "type": "string"
                },
                "optional": {
                    "type": "boolean"
                },
                "reference": {
                    "type": "string"
                },
                "classes": {
                    "type": "array"
                }
            },
            "additionalProperties": false
        },
        "wsi": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "const": "wsi"
                },
                "description": {
                    "type": "string"
                },
                "optional": {
                    "type": "boolean"
                },
                "reference": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "class": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "const": "class"
                },
                "optional": {
                    "type": "boolean"
                },
                "reference": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        }
    }
}

=== theodore-evans/glomeruli-segmentation/kidney_segmentation_app.json
{
    "$schema": "./ead-app-schema-draft-1.json",
    "name": "HuBMAP Kidney Segmentation App",
    "namespace": "org.empaia.empaia.hubmap-hacking-kidney.v1",
    "description": "Kidney segmentation algorithm for detection and counting of glomeruli in kidney WSI data",
    "inputs": {
        "kidney_wsi": {
            "type": "wsi"
        },
        "my_rectangle": {
            "type": "rectangle"
        }
    },
    "outputs": {
        "glomerulus_count": {
            "type": "integer",
            "reference": "inputs.my_rectangle"
        },
        "glomeruli_polygons": {
            "type": "collection",
            "reference": "inputs.my_rectangle",
            "items": {
                "type": "polygon",
                "reference": "inputs.kidney_wsi"
            }
        }
    }
}
